[tool.poetry]
name = "sudoku-solver"
version = "0.1.0"
description = ""
authors = ["Vitolus <vito.davide00@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
numpy = "1.26.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
